### ISSUE TITLE
Not working with Vencord, apparently

### ISSUE THREAD

**Issue by 1101-trash** [PL7963/Discord-Mica#3]

**Comment by PL7963** [comment]
Can you share screenshot or any other information? It seems working for me on Vencord.

**Comment by Landixbtw** [comment]
Also using vencord. I want to use Darkmode but when enabling it vencord goes white. 
(Using Arch, dwm, vesktop)

**Comment by PL7963** [comment]
> Also using vencord. I want to use Darkmode but when enabling it vencord goes white. 
> (Using Arch, dwm, vesktop)
Have you enabled Window transparency?

**Comment by Landixbtw** [comment]
For Vesktop ? No, not yet. Is the transparency bound to the color ?

**Comment by PL7963** [comment]
> For Vesktop ? No, not yet. Is the transparency bound to the color ?

Not really. But when there's no transparency electron defaults white as background. Which makes Vencord goes white.

**Comment by Landixbtw** [comment]
Ill try it.

**Comment by PL7963** [comment]
> So I did enable transparency via picom. But it still defaults to white. 

I'm not familiar with Picom. But I guess it only change transparency of the window(? Since Electron already applied white background. Picom cannot make it transparent.  
Also I noticed this issue someone has similar issue with vesktop Vencord/vesktop#433 . It seems has been fixed in 1.5.1 update. Have you upgraded to this version?
