### ISSUE TITLE
Transparency on the "You are reading old messages..." menu

### ISSUE THREAD

**Issue by Blackstonecoden** [PL7963/Discord-Mica#7]
![image](https://github.com/user-attachments/assets/7922eba9-ceb3-4971-88b2-54425a5d936f)
The menu just needs transparency, not blur so it should work 😉

**Comment by Blackstonecoden** [comment]
![image](https://github.com/user-attachments/assets/e4662964-846b-416c-8503-4b129cb57f7c)
Emoji selector has some glitches too

**Comment by PL7963** [comment]
> ![image](https://private-user-images.githubusercontent.com/87016780/398430759-7922eba9-ceb3-4971-88b2-54425a5d936f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMTY1NjcsIm5iZiI6MTczNTIxNjI2NywicGF0aCI6Ii84NzAxNjc4MC8zOTg0MzA3NTktNzkyMmViYTktY2ViMy00OTcxLTg4YjItNTQ0MjVhNWQ5MzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEyMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZTY0NGQ4OWMwMzU1ODYzZjZlNDYxMmIzMTgxN2E4OWI4ZTgyYmI2YzgwYjdmNjllMjZiYTI2OWYwMTQ0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U_LeJ_pzPV7qzTGsv0kG0eB_J7YL3IldcTNhTyrUL2k) The menu just needs transparency, not blur so it should work 😉

Make this transparent or semi-transparent one might encounter visibility issues since text could display behind of it. It's possible to make texts display higher. But looks having a little too much spaces. So I added new variables  `--dark-background-accent` and `--dark-background-accent`. You can set them to transparent or any other colors. 

And the emoji selector has been fixed!
